---
title: "GLM_Plotting for HCC1569"
author: "Chun-Han Lin"
date: "3/7/2017"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global, include = FALSE}
# Load packages
suppressMessages(library(ggplot2))
suppressMessages(library(reshape2))
suppressMessages(library(grid))
suppressMessages(library(gridExtra))
suppressMessages(library(shiny))
suppressMessages(library(BoutrosLab.plotting.general))
suppressMessages(library(factoextra))

# Load pre-processed data
load('/Users/Walkon302/Desktop/11112015_RE/GLM_means_HCC1569.RData')
load('/Users/Walkon302/Desktop/11112015_RE/HCC1569_HER2_GLM.RData')
load('/Users/Walkon302/Desktop/11112015_RE/HCC1569_pca.RData')

# Removed the SE column and rename the data
glm.other.means <- glm.other.means[-6]
glm.other.means.HER2 <- glm.other.means.HER2[-6]

# Select data with only drug treatments.
glm.other.means.HER22 <- subset(glm.other.means.HER2, Treatment != 'DMSO')

# Calculation of PCA
####
res.pca <- prcomp(zsc.all[6:19], center=FALSE, scale=FALSE) # data already centered and scaled
eig <- (res.pca$sdev)^2
variance <- eig*100/sum(eig)
cumvar <- cumsum(variance)
####

# Set up the limit of y-axis
edu_min <- min(glm.other.means$`adjusted mean`)
edu_max <- max(glm.other.means$`adjusted mean`)
her2_min <- min(glm.other.means.HER2$`adjusted mean`)
her2_max <- max(glm.other.means.HER2$`adjusted mean`)
```

```{r functions, include = FALSE}
# Define the functions
# Create the list of available columns
generatelist <- function(name) {
  fulllist <- list()
  for (i in seq_along(colnames(name))) {
    fulllist[i] = colnames(name)[i]
  }
  return(fulllist)
}

# Prepare the data for plotting single component of GLM analysis
glmdata1 <- function(data, cname) {
  datamean <- dcast(data, paste(cname, "~."), mean)
  datasd <- dcast(data, paste(cname, "~."), sd)
  datan <- dcast(data, paste(cname, "~."), length)
  datase <- datasd[2]/sqrt(datan[2])
  rownames(datamean) <- datamean[,1]
  result <- cbind(datamean, datase)
  colnames(result) <- c(cname, 'mean', 'se')
  return(list(result, cname))
}

# Prepare the data for plotting pairwise interactions of GLM analysis
glmdata2 <- function(data, rname, cname) {
  result <- dcast(data, paste(rname, "~", cname), mean)
  rownames(result) <- result[,1]
  return(list(result, rname, cname))
}

# Create the bar plot for single component of GLM analysis
glmline <- function(data, ytitle, min, max) {
  result <- ggplot(data[[1]], aes_string(data[[2]], 'mean')) + 
    geom_bar(stat = 'identity', aes_string(fill = colnames(data[[1]][1]))) +
    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.25) + 
    labs(x = data[[2]], y = ytitle) + theme_bw() + 
    theme(axis.text = element_text(size = rel(2)), axis.title = element_text(size = rel(2)),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
          axis.title.y = element_text(vjust = 0.5), 
          legend.text = element_text(size = rel(2)),
          legend.title = element_text(size = rel(2))) +
    coord_cartesian(ylim = c(min,max))
  return(result)
}

# Create the heatmap plot for pairwise interactions of GLM analysis
glmplot <- function(data) {
  nr <- nrow(data[[1]])
  result <- create.heatmap(
  x = data[[1]][1:nr, -1],
  xlab.label = data[[2]],
  ylab.label = data[[3]],
  xaxis.lab = NA,
  yaxis.lab = NA,
  xaxis.cex = rel(2),
  yaxis.cex = rel(2),
  xlab.cex = rel(2),
  ylab.cex = rel(2),
  style = 'Nature',
  xaxis.fontface = 1,
  yaxis.fontface = 1,
  colourkey.cex = 1,
  cluster.dimensions = 'both',
  colour.alpha = 1,
  cols.distance.method = "euclidean",
  legend.cex = 1.5,
  top.padding = 0.5,
  grid.row = TRUE,
  grid.col = TRUE,
  width = 5,
  height = 5,
  colour.scheme = c('blue', 'white', 'red'),
  #covariates.top = sample.covariate,
  #covariate.legend = sample.cov.legend,
  resolution = 600
  )
  return(result)
}


```

Box Graph
===
Input {.sidebar}
---
```{r featurebox, echo = FALSE}
# Generate the list of conditions.
inputPanel(
  selectInput("condition", label = h4("Select a condition"),
              choices = c('DMSO', 'Lapatinib', 'LapVP', 'All'),
              multiple = FALSE)
)

# Store entire EdU data as a reactive Shiny object
datadfEdU <- reactive({
  result <- glm.other.means
  return(result)
  })

# Store a entire pHER2/HER2 data as a reactive Shiny object
datadfHER2 <- reactive({
  result <- glm.other.means.HER2
  return(result)
})

# Store selected condition as a reactive Shiny object
condition <- reactive({
  result <- input$condition
  return(result)
})

# Store EdU data based on selected condition as a reactive Shiny object
datasubdfEdU <- reactive({
  ifelse(condition() == 'All', result <- datadfEdU(), result <- subset(datadfEdU(), Treatment == condition()))
  return(result)
})

# Store pHER2/HER2 data based on selected condition as a reactive Shiny object
datasubdfHER2 <- reactive({
  ifelse(condition() == 'All', result <- datadfHER2(), result <- subset(datadfHER2(), Treatment == condition()))
  return(result)
})

# Genearte the list of feature
inputPanel(
  selectInput("inputfeature", label = h4("Select a feature"),
            choices = generatelist(glm.other.means)[c(which(sapply(glm.other.means, is.factor)))],
            multiple = FALSE)
)

# Store the selected feature as an reactive Shiny object
feature <- reactive(input$inputfeature)

# Store the EdU data based on condition and feature as a Shiny object
gd1EdU <- reactive({
  result <- glmdata1(datasubdfEdU(), feature())
  return(result)
})

# Store the pHER2/HER2 data based on condition and feature as a Shiny object
gd1HER2 <- reactive({
  result <- glmdata1(datasubdfHER2(), feature())
  return(result)
})
```

row
---
### Drug Response
```{r, echo = FALSE}

# Plot bar plot of EdU data selected based on condition and feature.
renderPlot({
  p <- glmline(gd1EdU(), 'EdU Incorporation \n (% DMSO Control)', 0, 130)
  p
})
```

### pHER2/HER2 Status
```{r, echo = FALSE}
# Plot bar plot of pHER2/HER2 data selected based on condition and feature.
renderPlot({
  p <- glmline(gd1HER2(), 'pHER2/HER2 \n (Arbitrary Unit)', her2_min, her2_max)
  p
})
```

HeatMap
===
Input {.sidebar}
---
```{r, echo = FALSE}
# Generate the list of features.
inputPanel(
  selectInput("inputfeature1", label = h4("Select a feature"),
            choices = generatelist(glm.other.means)[c(which(sapply(glm.other.means, is.factor)))],
            multiple = FALSE),
  selectInput("inputfeature2", label = h4("Select a feature"),
            choices = generatelist(glm.other.means)[c(which(sapply(glm.other.means, is.factor)))],
            multiple = FALSE)
)
feature1 <- reactive(input$inputfeature1)
feature2 <- reactive(input$inputfeature2)

# Store the pHER2/HER2 data without DMSO treatment as a Shiny object
datadf2HER2 <- reactive({
  result <- glm.other.means.HER22
  return(result)
  })

# Store the EdU data based on two features as a Shiny object 
gd2EdU <- reactive({
  result <- glmdata2(datadfEdU(), feature1(), feature2())
  return(result)
})

# Store the pHER2/HER2 data based on two features as a Shiny object 
gd2HER2 <- reactive({
  result <- glmdata2(datadf2HER2(), feature1(), feature2())
  return(result)
})
```

row
---
### Drug Response
```{r, echo = FALSE}

# Plot heatmap of EdU data based on selected two features.
renderPlot({
  p <- glmplot(gd2EdU())
  p
})
```

### pHER2/HER2 Status
```{r, echo = FALSE}

# Plot heatmap of pHER2/HER2 data based on selected two features.
renderPlot({
  p <- glmplot(gd2HER2())
  p
})
```


PCA
===
row
---
### ECM 
```{r, echo = FALSE}
# Plot PCA individua factor map plot colored by ECM
renderPlot({
  p <- fviz_pca_ind(res.pca, label = "none", axes = c(1,2), habillage = zsc.all$ECM,
                   addEllipses=TRUE, ellipse.level=0.95, labelsize = 2) +
    theme(text = element_text(size = rel(4.5)), legend.text=element_text(size=rel(4.8)), 
          axis.text.x = element_text(size = rel(4.5)), axis.text.y = element_text(size = rel(4.5)),
          plot.title = element_text(size = rel(4.5)))
  p
})
```

### Ligand
```{r, echo = FALSE}
# Plot PCA individua factor map plot based on ligand
renderPlot({
  p <- fviz_pca_ind(res.pca, label = "none", axes = c(1,2), habillage = zsc.all$Ligand,
                   addEllipses=TRUE, ellipse.level=0.95, labelsize = 2) +
    theme(text = element_text(size = rel(4.5)), legend.text=element_text(size=rel(4.5)), 
          axis.text.x = element_text(size = rel(4.5)), axis.text.y = element_text(size = rel(4.5)),
          plot.title = element_text(size = rel(4.5)))
  p
})
```

row
---
### Treatment
```{r, echo = FALSE}
# Plot PCA individua factor map plot based on Treatment
renderPlot({
  p <- fviz_pca_ind(res.pca, label = "none", axes = c(1,2), habillage = zsc.all$Treatment,
                   addEllipses=TRUE, ellipse.level=0.95, labelsize = 2) +
    theme(text = element_text(size = rel(4.5)), legend.text=element_text(size=rel(4.5)), 
          axis.text.x = element_text(size = rel(4.5)), axis.text.y = element_text(size = rel(4.5)),
          plot.title = element_text(size = rel(4.5)))
  p
})
```

### Stiffness
```{r, echo = FALSE}
# Plot PCA individua factor map plot based on Stiffness
renderPlot({
  p <- fviz_pca_ind(res.pca, label = "none", axes = c(1,2), habillage = zsc.all$Stiffness,
                   addEllipses=TRUE, ellipse.level=0.95, labelsize = 2) +
    theme(text = element_text(size = rel(4.5)), legend.text=element_text(size=rel(4.5)), 
          axis.text.x = element_text(size = rel(4.5)), axis.text.y = element_text(size = rel(4.5)),
          plot.title = element_text(size = rel(4.5)))
  p
})
```